import type { NextPage } from 'next'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import SignInForm from 'components/SignInForm/SignInForm'
import ChannelBar from 'components/ChannelBar/ChannelBar'
import SideBar from 'components/SideBar/SideBar'
import WelcomeChannel from 'components/WelcomeChannel/WelcomeChannel'
import LoadingSpinner from 'components/LoadingSpinner/LoadingSpinner'
import { collection, onSnapshot, query } from '@firebase/firestore'
import { auth, db } from 'firebase-config'
import { useAuthState } from 'react-firebase-hooks/auth'

const Home: NextPage = ({
  users,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [user, loading, error] = useAuthState(auth)

  if (loading) {
    return (
      <div className='flex h-screen items-center justify-center'>
        <LoadingSpinner />
      </div>
    )
  }

  if (!user) {
    return (
      <div className='flex h-screen items-center justify-center'>
        <SignInForm />
      </div>
    )
  }

  if (error) {
    return (
      <div className='flex h-screen items-center justify-center'>
        <h3 className='text-red-500'>{error}</h3>
      </div>
    )
  }

  return (
    <>
      <Head>
        <title>Chatify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex h-screen'>
        <div className='hidden md:flex'>
          <SideBar />
          <ChannelBar />
        </div>
        <WelcomeChannel users={users} />
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const users: { id: string }[] = []

  onSnapshot(query(collection(db, 'users')), (snapshot) => {
    snapshot.docs.map((doc) => {
      users.push({
        ...doc.data(),
        id: doc.id,
      })
    })
  })

  return {
    props: { users: JSON.stringify(users) },
  }
}

export default Home
